languages: node_js
node_js:
  - 12

services:
  - docker

insall:
  - echo "nothing need to be installed"

before_script:
  - echo "All test are passed"

script:
  - docker --version
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user

  - docker tag udagram-reverseproxy cuong2305/udagram-reverseproxy:v1
  - docker tag udagram-api-feed cuong2305/udagram-api-feed:v1
  - docker tag udagram-api-user cuong2305/udagram-api-user:v1

after_success:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - docker push cuong2305/udagram-reverseproxy:v1
  - docker push cuong2305/udagram-api-feed:v1
  - docker push cuong2305/udagram-api-user:v1
